version: "3.9"

services:
  backend:
    build: ./backend
    image: backend
    container_name: backend-container
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: admin
      DB_PORT: 3306

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend-container
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
